### ISSUE TITLE
Expectation of attending the entire week

### ISSUE THREAD

**Issue by jakevdp** [AstroHackWeek/AstroHackWeek2018#9] opened 2017-08-29 00:02 UTC
We should add a check-box in the application specifying this (especially for locals)

**Comment by adrn** [comment] 2017-08-29 18:44
Duplicate of #2?

**Comment by dhuppenkothen** [comment] 2017-08-29 18:45
Oops, that must have come up before in our discussions. I'm closing this then. :)

**Closed by dhuppenkothen** 2017-08-29 18:45 UTC
